import Head from "next/head";
import style from "../styles/layout.module.css";
import Navbar from "./navbar";

export default function Layout({children, title}) {
    return(
        <div>
            <Head>
                <title>{title ? `Gestión | ${title}` : "Gestión"}</title>
                <meta name="description" content="Generated by create next app"></meta>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <div className={style.container}>
                {children}
            </div>
        </div>
    );
}